### ISSUE TITLE
Unable to get informations when using an uploaded key

### ISSUE THREAD

**Issue by didieraupest** [Nicologies/PrExtras#2]
Hello, 

I have tried to use this plugin and encountered some issues with TeamCity 10.0.3.
I am trying to use this with github enterprise.
Our server is a bit slow, and I encountered some timeout. Maybe, a `timeout` parameter could be usefull ?

When setting the `fetch URL` of my VCS Root in SSH Style: `<server>:<owner>/<repo>.git` an error occured: ` unable to get owner from url <server>:<owner>/<repo>.git`.

Without that, I can't use an Uploaded key as an Authentication method.

**Comment by EbenZhang** [comment]
Github Enterprise hasn't been supported. I will try implement this feature.

Is the VCSRoot `ssh://<myserver>:<owner>/<repo>.git`? or `<server>:<owner>/<repo>.git`

**Comment by EbenZhang** [comment]
Add the support for GitHub Enterprise: https://github.com/Nicologies/PrExtras/releases/tag/1.0.8
you need to define a system property to let the plugin know where is API server, see https://github.com/Nicologies/PrExtras#github-enterprise

I tested GitHub enterprise using the VCSRoot of `git@githubserver.com:owner/repo.git` (`ssh://<myserver>:<owner>/<repo>.git` should also be fine but I wasn't able to test it)

**Comment by didieraupest** [comment]
Hello 
I guess, there is something wrong: 

```
[14:53:09]Step 1/1: Get All Informations (PullRequest Extra Info)
[14:53:10]GitHub API URL: https://api.github.com
[14:53:10]Owner cannot be null
[14:53:10]
java.lang.IllegalArgumentException: Owner cannot be null
	at org.eclipse.egit.github.core.RepositoryId.<init>(RepositoryId.java:106)
	at com.nicologies.prextras.RepoInfoParser.Parse(RepoInfoParser.kt:10)
	at com.nicologies.prextras.BuildService.getRepositoryId(BuildService.java:232)
	at com.nicologies.prextras.BuildService.beforeProcessStarted(BuildService.java:47)
	at jetbrains.buildServer.agent.runner2.SingleCommandLineBuildSessionAdapter.beforeProcessStarted(SingleCommandLineBuildSessionAdapter.java:58)
	at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.executeProcess(GenericCommandLineBuildProcess.java:62)
	at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.waitFor(GenericCommandLineBuildProcess.java:269)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:75)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:295)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:53)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:259)
	at java.lang.Thread.run(Thread.java:745)
```

Api URL does not seems to match my local git. I will try to check if I found something inside your code that might be usefull.
